version: '3.8'
volumes:
  postgres:
services:
  postgres:
    image: "postgres:13-alpine"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "ledger"
      POSTGRES_PASSWORD: "ledger"
      POSTGRES_DB: "ledger"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  ledger:
    #image: "ghcr.io/numary/ledger:latest"
    image: golang:1.16-alpine
    command: go run main.go server start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3068/_info"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3068:3068"
    volumes:
      - .:/src
    working_dir: /src
    environment:
      CGO_ENABLED: 0
      NUMARY_DEBUG: "true"
      NUMARY_STORAGE_DRIVER: "postgres"
      NUMARY_STORAGE_POSTGRES_CONN_STRING: "postgresql://ledger:ledger@postgres/ledger"
      NUMARY_SERVER_HTTP_BIND_ADDRESS: "0.0.0.0:3068"
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  control:
    image: "ghcr.io/numary/ledger:latest"
    command: numary ui
    depends_on:
      ledger:
        condition: service_healthy
    ports:
      - "3078:3078"
    environment:
      NUMARY_UI_HTTP_BIND_ADDRESS: "0.0.0.0:3078"

  jaeger:
    image: "jaegertracing/all-in-one"
    ports:
      - "16686:16686/tcp"

