openapi: 3.0.0

info:
  title: Numary Ledger API
  version: 1.0-beta

servers:
  - url: http://localhost:3068
    description: local

components:
  parameters:
    cursorAfter:
      in: query
      name: after
      required: false
      schema:
        type: string
      description: Used for cursor-based pagination, indicates that you want items with ID < after
  schemas:
    reference:
      type: string
    asset:
      type: string
    account:
      type: object
    stats:
      type: object
      properties:
        reference:
          $ref: "#/components/schemas/reference"
        balances:
          type: object
          additionalProperties:
            type: "integer"
        metadata:
          type: object
    posting:
      type: object
      properties:
        source:
          $ref: "#/components/schemas/reference"
        destination:
          $ref: "#/components/schemas/reference"
        amount:
          type: integer
        asset:
          $ref: "#/components/schemas/asset"
    transaction:
      type: object
      properties:
        reference:
          description: a unique reference (e.g. an ID in your system)
          type: string
        postings:
          type: array
          items:
            $ref: "#/components/schemas/posting"
        timestamp:
          type: string
        hash:
          type: string
        metadata:
          type: object
    script:
      type: object
      properties:
        plain:
          type: string
        vars:
          type: object

paths:
  /_info:
    get:
      summary: Server infos
      responses:
        200:
          description: server info object
          content:
            application/json:
              schema:
                type: object

  /{ledger}/accounts:
    get:
      summary: List accounts
      parameters:
        - $ref: "#/components/parameters/cursorAfter"
      responses:
        200:
          description: The accounts list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/account"

  /{ledger}/stats:
    get:
      summary: Stats accounts
      responses:
        200:
          description: The stats for account
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/stats"
  /{ledger}/accounts/{reference}:
    get:
      summary: Get an account by its fully-qualified reference
      parameters:
        - required: true
          name: ledger
          in: path
          schema:
            type: string
        - required: true
          name: reference
          in: path
          schema:
            $ref: "#/components/schemas/reference"
        - $ref: "#/components/parameters/cursorAfter"
      responses:
        200:
          description: The account object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/account"

  /{ledger}/accounts/{reference}/metadata:
    post:
      summary: Set metadata on account
      parameters:
        - required: true
          name: ledger
          in: path
          schema:
            type: string
        - required: true
          name: reference
          in: path
          schema:
            $ref: "#/components/schemas/reference"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Success

  /{ledger}/transactions:
    get:
      summary: List transactions
      parameters:
        - required: true
          name: ledger
          in: path
          schema:
            type: string
        - $ref: "#/components/parameters/cursorAfter"
        - required: false
          name: account
          in: query
          schema:
            type: string
      responses:
        200:
          description: The transactions list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
    post:
      summary: Commit a new transaction to the ledger
      parameters:
        - required: true
          name: ledger
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/transaction"

      responses:
        200:
          description: Successful commit

  /{ledger}/transactions/{reference}/metadata:
    post:
      summary: Set metadata on transaction
      parameters:
        - required: true
          name: ledger
          in: path
          schema:
            type: string
        - required: true
          name: reference
          in: path
          schema:
            $ref: "#/components/schemas/reference"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Success

  /{ledger}/script:
    post:
      summary: Execute Numscript
      parameters:
        - required: true
          name: ledger
          in: path
          schema:
            type: string
      responses:
        200:
          description: successful execution
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/script"
