on:
  push:
    branches:
      - main
name: Main
jobs:
  oas:
    name: 'OAS Readme'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}
          oas-file-path: './spec/http.yml'
          api-version: 'v1.0.0'
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: get deps
        run: CGO_ENABLED=1 go get
      - name: fetch numary control
        run: make fetch-control
      - name: prepare goreleaser
        run: cp .github/.goreleaser.linux.yml .goreleaser.yml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --parallelism 4 --rm-dist --skip-validate --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
