name: Pull Request - Open
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  Test:
    name: 'Test'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: get deps
        run: go get
      - name: fetch numary control
        run: make fetch-control
      - name: run tests
        run: go test -v -coverpkg=./... -coverprofile=coverage.out ./...
  Lint:
      name: 'Lint'
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      steps:
        - uses: actions/setup-go@v2
          with:
            go-version: '1.16'
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
        - name: get deps
          run: go get
        - name: run vet
          run: go vet .
