name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - uses: actions/checkout@v2

      - name: get deps
        run: go get

      - name: run tests
        run: go test -v -coverpkg=./... -coverprofile=coverage.out ./...
