---
volumes:
  postgres:
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
  postgres:
    extends:
      file: ../../docker-compose.yml
      service: postgres
  ledger:
    extends:
      file: ../../docker-compose.yml
      service: ledger
    depends_on:
      - postgres
    environment:
      NUMARY_EVENT_BUS_KAFKA_ENABLED: "true"
      NUMARY_EVENT_BUS_KAFKA_BROKER: "kafka:9002"
      NUMARY_EVENT_BUS_TOPIC: "*:default" # Send all to 'default' topic